spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    username: root
    password: mass1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/survivalism?UTF-8